version: "3.8"

services:
  app:
    build: .
    container_name: app-backend
    hostname: app-backend
    networks:
      - app-network
    depends_on:
      - db
    ports:
      - 8080:8080

  db:
    image: postgres:latest
    container_name: db-postgres
    hostname: db-postgres
    networks:
      - app-network
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
